### ISSUE TITLE
After `npm upgrade` from 4.0.2 => 4.2, get   `Cannot find module './util.js'`

### ISSUE THREAD

**Issue by gregglind** [popeindustries/inline-source#25]
New installs are unaffected.  

(I don't have a good solution)
```
> require("inline-source")
Error: Cannot find module './util.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/glind/junk/sr2/node_modules/inline-source/node_modules/csso/lib/cssoapi.js:1:74)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

```
inline-source@4.2.0 /Users/glind/junk/sr2/node_modules/inline-source
├── csso@1.3.11
├─┬ htmlparser2@3.8.3
│ ├── UNMET DEPENDENCY domelementtype@1
│ ├── UNMET DEPENDENCY domhandler@2.3
│ ├── UNMET DEPENDENCY domutils@1.5
│ ├── UNMET DEPENDENCY entities@1.0
│ └── UNMET DEPENDENCY readable-stream@1.1
├── UNMET DEPENDENCY lodash@~3.10.1
├─┬ svgo@0.5.6
│ ├── UNMET DEPENDENCY coa@~1.0.1
│ ├── UNMET DEPENDENCY colors@~1.1.2
│ ├── UNMET DEPENDENCY js-yaml@~3.3.1
│ ├── UNMET DEPENDENCY mkdirp@~0.5.1
│ ├── UNMET DEPENDENCY sax@~1.1.1
│ └── UNMET DEPENDENCY whet.extend@~0.9.9
└─┬ uglify-js@2.4.24
  ├── UNMET DEPENDENCY async@~0.2.6
  ├── UNMET DEPENDENCY source-map@0.1.34
  ├── UNMET DEPENDENCY uglify-to-browserify@~1.0.0
  └── UNMET DEPENDENCY yargs@~3.5.4
```

**Comment by gregglind** [comment]
Maybe helpful?
```
49696 glind ~/junk/sr2/node_modules/inline-source $ npm-check-updates -u
You can now use ncu for less typing!

 csso       1.3.11  →  1.4.1
 svgo        0.5.6  →  0.6.0
 uglify-js  2.4.24  →  2.5.0
```

**Comment by popeindustries** [comment]
I'm not sure I follow. A clean install works, but not an update? I've had problems migrating to npm@3, though wiping `node_modules` and doing a full install usually solves the problem. 

I have an issue I need to fix with svg inlining, so I'll be updating those dependencies soon.

**Comment by gregglind** [comment]
Correct.  As I say, I have no idea of why.   Observation :)

**Comment by popeindustries** [comment]
Alright, thanks for taking the time to report the problem. It looks to me like an npm issue, so I'll close his for now.
