### ISSUE TITLE
Simply inline a SVG Sprite across all pages

### ISSUE THREAD

**Issue by custa1200** [popeindustries/inline-source#29]
How would I go about using this to inline a SVG Sprite across all pages on my site. I'm using Express JS.

**Comment by popeindustries** [comment]
At work we use express.js with nunjucks templates (precompiling the template on application startup):

```js
<!DOCTYPE html>
<html lang="{{ langCode }}" class="no-js {{ id }}">

  {% include "../../lib/templates/head.nunjs" %}

  <body>
  {% if includeDefs %}
    <img inline src="../../../node_modules/@yr/icons/graphicsDefs.svg">
    <img inline src="../../../node_modules/@yr/weather-symbols/graphicsDefs.svg">
  {% endif %}
```

You can pass any string directly to inline-source, so a templating language isn't really even necessary.

**Comment by custa1200** [comment]
I am using Handlebars for my templating,  In my ap.js I have:

```
var inline = require('inline-source');
```
and in my HTML Layout page I have:
```
  <!doctype html>
  {{#block "html"}}
  {{>page/html schema="AboutPage"}}
  {{/block}}
  <head>
    {{>page/head}}
    {{>page/social}}
    {{>page/favicon}}
    {{>script/newrelic}}
    {{{block "head"}}}
  </head>
  {{#block "bodyTag"}}
  <body>
  {{/block}}
    <img inline src="/images/defs/svg/sprite.defs.svg" />
    <div class="remodal-bg">
      {{#if @baselineGrid}}<div class="page__baseline page__baseline--{{@baselineGrid}}"></div>{{/if}}
      {{>page/page_header user=user}}
      <main class="page-main">
        {{>page/alerts}}
        {{{body}}}
      </main>
      {{>page/page_footer}}
    </div>
    {{>modal/sign_in}}
    {{>script/global}}
    {{{block "scripts"}}}
    {{>script/analytics}}
  </body>
  </html>
```

But I am not sure how to ensue that the sprite.def.svg file is inlined, because atm it's not. Should I be writing a handlebars helper or something? :(

**Comment by popeindustries** [comment]
basically, all you need to do is load the template file, pass the file contents to inline-source, then pass the results to handlebars:

```js
var fs = require('fs')

```

**Comment by custa1200** [comment]
Hey there, I'm still having a few issues.

The layout file I am using to call the helper looks like:
``` handlebars
...
<body>
    {{inlineSVG "svgsprite.hbs"}}
    ..
```

My "svgsprite.hbs" file template is
```html
<img inline src="/images/defs/svg/sprite.defs.svg" />
```
and my Handlebars helper is:
``` javascript
hbs.registerHelper("inlineSVG", function(url) {

    var partialPath = __dirname + "/views/partials/inline-svg/" + url;
    console.log("Partial Path: " + partialPath); // /Users/custa/github/Portfolio/portfolioapp/views/partials/inline-svg/svgsprite.hbs

    var inlineSVG = inline.sync(partialPath, {
      compress: true,
      rootpath: path.resolve('public')
    });
    console.log("Inline SVG: " + inlineSVG); // <img inline src="/images/defs/svg/sprite.defs.svg" />

    return inlineSVG;

});
```

but the end result renderer in the page is just the following text as text `<img inline src="/images/defs/svg/sprite.defs.svg" />` not an image and not the inlined SVG code. When I tried to wrap the inline in a hbs.precompile()  Handlebars crashed with the following error
```
Error
 at Object.<anonymous> (/Users/custa/github/Portfolio/portfolioapp/node_modules/hbs/node_modules/handlebars/dist/cjs/handlebars/exception.js:29:23)
 at Module._compile (module.js:434:26)
 at Object.Module._extensions..js (module.js:452:10)
 at Module.load (module.js:355:32)
 at Function.Module._load (module.js:310:12)
 at Function.cls_wrapMethod [as _load] (/Users/custa/github/Portfolio/portfolioapp/node_modules/newrelic/lib/shimmer.js:230:38)
 at Module.require (module.js:365:17)
 at require (module.js:384:17)
 at Object.<anonymous> (/Users/custa/github/Portfolio/portfolioapp/node_modules/hbs/node_modules/handlebars/dist/cjs/handlebars/base.js:3:17)
 at Module._compile (module.js:434:26)
```

**Comment by custa1200** [comment]
Still can't get this to work :( 

```
hbs.registerHelper("inlineSVG", function(url) {

    var partialPath = __dirname + "/views/partials/inline-svg/" + url;

    var inlineSVG = inline.sync(partialPath, {
      compress: true,
      rootpath: path.resolve('public')
    });
    return inlineSVG;
});
```
only retursn the contens of the partial and doesn't return the content inlined.

**Comment by custa1200** [comment]
if I set svgAsImage to true it outpus the SVG contents as text in the src attribute.

**Comment by custa1200** [comment]
So I tried the precompile route with the following code: 
``` javascript
app.locals.svgSprite = hbs.handlebars.precompile(inline.sync(__dirname + "/views/partials/inline-svg/svgsprite.hbs"));
```
but when I console.log app.locals.svgSprite I get the following: 
```
{"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
    return "<img inline src=\"/public/images/defs/svg/sprite.svg\" />";
},"useData":true}
```
So even with the precompiling I can't seem to get it to work, it is just outputting the contents of the svgsprite.hbs file without actually inlining the sprite.svg file  :(
